version: 0.0
os: linux
files:
  - source: /aws
    destination: /home/ec2-user/app
permissions:
  - object: /home/ec2-user/app/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: aws/scripts/before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: aws/scripts/after-install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: aws/scripts/application-start.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: aws/scripts/validate-service.sh
      timeout: 300
      runas: ec2-user
